### ISSUE TITLE
pull-request for GitHub Enterprise over http doesn't work

### ISSUE THREAD

**Issue by Madrigal** [owenthereal/gh#220]
My GHE host doesn't accept https, so I have to access via http. I've seen from https://github.com/jingweno/gh/pull/115 that you can specify the full host with scheme when adding a host, so my config looks like 

```
gh.host=http://github.enterprise.com
```

Commands like `gh push` work ok, but `gh pull-request` gives me 

```
fatal: Aborted: the origin remote doesn't point to a GitHub repository.
```

If I specify the gh.host to github.enterprise.com I got prompted for my credentials but my GHE rejects the https connection.
I've tried setting up gh protocol to http like in Hub (https://github.com/github/hub#https-instead-of-git-protocol) and putting the host without the scheme but it doesn't seem to work. Can you give me a hand with this?

**Comment by raine** [comment]
```
hub version 2.2.0-rc1-g111100c
```

Installed with `brew install --HEAD hub`

I am getting 

```
Aborted: the origin remote doesn't point to a GitHub repository.
```

with `gh.host=http://github.enterprise.com`
